export const food_categories = "All Categories";
export const items = "items";
export const item_details = "item_details";
export const search = "search";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const Update_cart = "Update_cart";
export const Update_item_cart = "Update_item_cart";
export const related_items = "related_items";
